version: "3.8"

services:
  postgres:
    # บริการ PostgreSQL ใช้สำหรับรันฐานข้อมูล
    image: postgres:latest # ใช้ Image Docker ของ PostgreSQL เวอร์ชันล่าสุด
    container_name: postgres-go-project # ตั้งชื่อคอนเทนเนอร์ว่า "postgres"
    environment:
      POSTGRES_DB: mydatabase # ชื่อฐานข้อมูลเริ่มต้นที่สร้างขึ้น
      POSTGRES_USER: myuser # ชื่อผู้ใช้สำหรับการเชื่อมต่อกับฐานข้อมูล
      POSTGRES_PASSWORD: mypassword # รหัสผ่านของผู้ใช้
    volumes:
      - postgres_data:/var/lib/postgresql/data # กำหนด volume เพื่อเก็บข้อมูลฐานข้อมูลอย่างถาวร
    ports:
      - "5432:5432" # เปิดพอร์ต 5432 เพื่อให้เข้าถึง PostgreSQL จากภายนอก
    restart: unless-stopped # คอนเทนเนอร์จะรีสตาร์ทโดยอัตโนมัติเว้นแต่จะถูกหยุด (stopped)

  pgadmin:
    # บริการ pgAdmin ใช้สำหรับการจัดการฐานข้อมูล PostgreSQL ผ่าน GUI
    image: dpage/pgadmin4:latest # ใช้ภาพ Docker ของ pgAdmin เวอร์ชันล่าสุด
    container_name: pgadmin # ตั้งชื่อคอนเทนเนอร์ว่า "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # อีเมลสำหรับล็อกอินเข้า pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # รหัสผ่านสำหรับล็อกอินเข้า pgAdmin
    ports:
      - "5050:80" # เปิดพอร์ต 5050 เพื่อเข้าถึง pgAdmin ผ่านเบราว์เซอร์ (http://localhost:5050)
    depends_on:
      - postgres # ให้บริการ pgAdmin เริ่มหลังจากที่ PostgreSQL พร้อมแล้ว
    restart: unless-stopped # คอนเทนเนอร์จะรีสตาร์ทโดยอัตโนมัติเว้นแต่จะถูกหยุด (stopped)

volumes:
  postgres_data: # volume สำหรับเก็บข้อมูลของฐานข้อมูล PostgreSQL อย่างถาวร
